# Site Settings
remote_theme: chrisrhymes/mere-blog-theme
title: Liz Metzger's Portfolio
tagline: Portfolio
email: liz.mtzgr.00@gmail.com
description: >
  I'm an MS in Robotics student at Northwestern.
baseurl: /portfolio
url: lizmetzger.github.io
permalink: pretty

paginate: 6
paginate_path: "/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Liz Metzger"
      layout: post
      image: /img/home.jpg
      show_sidebar: true
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

collections:
  authors:
    output: true